In [2]:
# A bit of setup

import numpy as np
import matplotlib.pyplot as plt

from cs231n.classifiers.neural_net import TwoLayerNet

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

In [3]:
input_size = 4
hidden_size = 10
num_classes = 3
num_inputs = 5

def init_toy_model():
  np.random.seed(0)
  return TwoLayerNet(input_size, hidden_size, num_classes, std=1e-1)

def init_toy_data():
  np.random.seed(1)
  X = 10 * np.random.randn(num_inputs, input_size)
  y = np.array([0, 1, 2, 2, 1])
  return X, y

net = init_toy_model()
X, y = init_toy_data()

In [22]:
dh1 = net.params['W2'].sum(axis=1)
dh1 * X

ValueError: operands could not be broadcast together with shapes (10,) (5,4) 

In [61]:
def prob_from_scores(scores):
    maxscore = np.max(scores, 1)
    shifted_scores = scores - maxscore[:,np.newaxis]
    probs = np.exp(shifted_scores) / np.sum(np.exp(shifted_scores), 1)[:,np.newaxis]
    return probs

In [79]:
reg = 0
W1, b1 = net.params['W1'], net.params['b1']
W2, b2 = net.params['W2'], net.params['b2']
N, D = X.shape

# Compute the forward pass
scores = None
#############################################################################
# TODO: Perform the forward pass, computing the class scores for the input. #
# Store the result in the scores variable, which should be an array of      #
# shape (N, C).                                                             #
#############################################################################
f = lambda x: np.maximum(x, 0)
h0 = X.dot(W1) + b1
h1 = f(h0)
#    maxscore = np.max(f1, 1)
#    f1_shifted = f1 - maxscore[:,np.newaxis]
#    h1 = np.exp(f1_shifted) / np.sum(np.exp(f1_shifted), 1)[:,np.newaxis]
scores = h1.dot(W2) + b2
#############################################################################
#                              END OF YOUR CODE                             #
#############################################################################

# Compute the loss
loss = None
#############################################################################
# TODO: Finish the forward pass, and compute the loss. This should include  #
# both the data loss and L2 regularization for W1 and W2. Store the result  #
# in the variable loss, which should be a scalar. Use the Softmax           #
# classifier loss. So that your results match ours, multiply the            #
# regularization loss by 0.5                                                #
#############################################################################
maxscore = np.max(scores, 1)
shifted_scores = scores - maxscore[:,np.newaxis]
probs = np.exp(shifted_scores) / np.sum(np.exp(shifted_scores), 1)[:,np.newaxis]
losses = -np.log( probs[xrange(N), y] )
loss = losses.sum() / N
loss += 0.5 * reg * (np.sum(W1*W1) + np.sum(W2*W2) + sum(b1*b1) + sum(b2*b2))
#############################################################################
#                              END OF YOUR CODE                             #
#############################################################################

# Backward pass: compute gradients
grads = {}
#############################################################################
# TODO: Compute the backward pass, computing the derivatives of the weights #
# and biases. Store the results in the grads dictionary. For example,       #
# grads['W1'] should store the gradient on W1, and be a matrix of same size #
#############################################################################
ds = (- true_indices + probs).sum(axis=0)
grads['W2'] = ds*h1.transpose().dot(scores)
grads['b2'] = ds*scores.sum(axis=0)
dh1 = (ds*W2).sum(axis=1)
dh0 = dh1*1*(np.maximum(h0, 0)>0)
grads['W1'] = X.transpose().dot(dh0)
grads['b1'] = dh0.sum(axis=0)

In [81]:
ds

array([ 1.04984549, -0.7159525 , -0.33389299])

In [70]:
print dh1.shape
print dh0.shape
print grads['W1'].shape
print grads['W2'].shape
print grads['b1'].shape
print grads['b2'].shape

(10,)
(5, 10)
(4, 10)
(10, 3)
(10,)
(3,)


In [73]:
#margindices.transpose().dot(X).transpose()
gradIncorrect = X.transpose().dot(margindices)
gradCorrect = np.sum(X*np.transpose([nOverflow]*D),1)
gradIncorrect[xrange(N),y] += np.sum(X*np.transpose([nOverflow]*D),1)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [76]:
nOverflow = margindices.sum(1)

true_indices = np.zeros(margindices.shape)
true_indices[xrange(N),y] = 1
margindices2 = true_indices* np.transpose([nOverflow]*K)
true_indices

array([[ 2.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.],
       [ 2.,  0.,  0.],
       [ 0.,  0.,  2.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [79]:
learning_rate=1e-3
reg=1e-5
num_iters=100
batch_size=200

In [82]:
num_train, dim = X.shape
num_classes = np.max(y) + 1

In [84]:
sampleIndices = np.random.choice(num_train, batch_size)
x_batch = X[sampleIndices]

In [87]:
x_batch.shape

(200, 5)

In [91]:
np.argmax(X.dot(w), 1)

array([2, 1, 0, 2, 2, 2, 2, 1, 1, 0])

In [93]:
W = w
num_classes = W.shape[1]
num_train = X.shape[0]
loss = 0.0
i=0
scores = X[i].dot(W)
maxscore = np.max(scores)
shifted_scores = scores - maxscore
prob = np.exp(shifted_scores[y[i]]) / np.sum(np.exp(shifted_scores))
loss += -np.log( prob )

In [94]:
probs = np.exp(shifted_scores) / np.sum(np.exp(shifted_scores))
probs

array([  2.22694417e-284,   1.36792233e-001,   8.63207767e-001])

In [124]:
scores = X.dot(W)
maxscore = np.max(scores, 1)
shifted_scores = scores - maxscore[:,np.newaxis]
probs = np.exp(shifted_scores) / np.sum(np.exp(shifted_scores), 1)[:,np.newaxis]

losses = -np.log( probs[xrange(num_train), y] )
loss = losses.sum() / num_train
true_indices = np.zeros(probs.shape)
true_indices[xrange(num_train),y] = 1
dW = - X.transpose().dot(true_indices - probs)
dW /= num_train

array([[-276.02673381, -144.03374628,  420.06048009],
       [ 117.48410423,    0.47107995, -117.95518419],
       [ 138.52086798,   74.29220512, -212.81307311],
       [-163.77482208, -209.58392787,  373.35874996],
       [ 431.44820255,  -44.34351608, -387.10468646]])

In [114]:
scores = X.dot(W)
maxscore = np.max(scores, 1)
shifted_scores = scores - maxscore[:,np.newaxis]
probs = np.exp(shifted_scores) / np.sum(np.exp(shifted_scores), 1)[:,np.newaxis]
probs

array([[  2.22694417e-284,   1.36792233e-001,   8.63207767e-001],
       [  1.85128273e-091,   1.00000000e+000,   3.15412608e-028],
       [  1.00000000e+000,   3.32622725e-230,   4.20033992e-208],
       [  9.94720573e-098,   2.10912742e-180,   1.00000000e+000],
       [  3.62125555e-234,   2.77751856e-053,   1.00000000e+000],
       [  3.07604800e-117,   3.44940788e-051,   1.00000000e+000],
       [  8.52309234e-179,   2.46700570e-165,   1.00000000e+000],
       [  1.08813177e-033,   1.00000000e+000,   6.60698816e-123],
       [  1.89696790e-138,   9.99999999e-001,   1.49548337e-009],
       [  1.00000000e+000,   8.09717014e-017,   3.70633181e-048]])

In [118]:
probs[xrange(num_train), y]

array([  2.22694417e-284,   1.00000000e+000,   4.20033992e-208,
         9.94720573e-098,   2.77751856e-053,   1.00000000e+000,
         8.52309234e-179,   6.60698816e-123,   9.99999999e-001,
         8.09717014e-017])

In [113]:
np.sum(np.exp(shifted_scores), 1)

array([ 1.15846965,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [7]:
import numpy as np
x = np.array([1, -1, 4])
np.maximum(x, 0)

array([1, 0, 4])